from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from polite_scraper.config import DEFAULT_BASE_URL, DEFAULT_USER_AGENT, ScraperConfig
from polite_scraper.pipeline import PoliteScraper


VERIFICATION_ROOT = ROOT / "verification"


def checkpoint(
    name: str,
    pages: list[int],
    cache_dir: Path,
    output_dir: Path,
    *,
    expected: str,
) -> dict[str, object]:
    try:
        config = ScraperConfig(
            base_url=DEFAULT_BASE_URL,
            user_agent=DEFAULT_USER_AGENT,
            timeout_seconds=10,
            min_delay_seconds=0.5,
            cache_dir=cache_dir,
            output_dir=output_dir,
        )
        report = PoliteScraper(config).run(pages, run_label=name)
        summary = report.to_dict()
        decisions = summary["robots_decisions"]
        safety_observed = (
            summary["request_timeout_seconds"] > 0
            and summary["minimum_throttle_seconds"] >= 0.5
            and all(decision["allowed"] is True for decision in decisions)
        )
        if expected == "clean":
            passed = (
                report.pages_succeeded == len(pages)
                and report.pages_failed == 0
                and safety_observed
                and summary["throttle_floor_observed"] is True
            )
        elif expected == "warm":
            passed = (
                report.pages_succeeded == len(pages)
                and report.pages_failed == 0
                and report.cache_hits == len(pages)
                and report.network_fetches == 0
                and safety_observed
                and summary["throttle_floor_observed"] is None
            )
        else:
            passed = (
                report.pages_failed == 1
                and report.pages_succeeded == len(pages) - 1
                and report.accepted_records > 0
                and safety_observed
                and summary["throttle_floor_observed"] is True
            )
        return {
            "name": name,
            "status": "PASS" if passed else "NOT_COMPLETED",
            "requested_pages": pages,
            "expected": expected,
            "observed": summary,
        }
    except Exception as exc:
        return {
            "name": name,
            "status": "NOT_COMPLETED",
            "requested_pages": pages,
            "expected": expected,
            "error": f"{type(exc).__name__}: {exc}",
        }


def main() -> int:
    runs = VERIFICATION_ROOT / "runs"
    if runs.exists():
        shutil.rmtree(runs)
    clean_cache = runs / "clean_cache" / "cache"
    clean_output = runs / "clean_cache" / "output"
    warm_cache = clean_cache
    warm_output = runs / "warm_cache" / "output"
    partial_cache = runs / "partial_failure" / "cache"
    partial_output = runs / "partial_failure" / "output"

    results = [
        checkpoint(
            "clean-cache-pages-1-3",
            [1, 2, 3],
            clean_cache,
            clean_output,
            expected="clean",
        ),
        checkpoint(
            "warm-cache-pages-1-3",
            [1, 2, 3],
            warm_cache,
            warm_output,
            expected="warm",
        ),
        checkpoint(
            "partial-failure-pages-1-2-and-unavailable-9999",
            [1, 2, 9999],
            partial_cache,
            partial_output,
            expected="partial",
        ),
    ]
    evidence = {
        "target": DEFAULT_BASE_URL,
        "user_agent": DEFAULT_USER_AGENT,
        "run_at": __import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat(),
        "checkpoints": results,
    }
    VERIFICATION_ROOT.mkdir(parents=True, exist_ok=True)
    evidence_path = VERIFICATION_ROOT / "observed_checkpoints.json"
    evidence_path.write_text(json.dumps(evidence, indent=2) + "\n", encoding="utf-8")
    markdown = [
        "# Verification Evidence",
        "",
        f"Target: `{DEFAULT_BASE_URL}`",
        f"User-Agent: `{DEFAULT_USER_AGENT}`",
        "",
        "This file is generated by `python tools/live_verification.py`. It records only observations from the run immediately above; a checkpoint marked `NOT_COMPLETED` is not presented as a success.",
        "",
    ]
    for result in results:
        markdown.extend(
            [
                f"## {result['name']}",
                "",
                f"- Status: **{result['status']}**",
                f"- Requested pages: `{result['requested_pages']}`",
                f"- Expected condition: `{result['expected']}`",
            ]
        )
        observed = result.get("observed")
        if isinstance(observed, dict):
            markdown.extend(
                [
                    f"- Pages attempted/succeeded/failed: `{observed['pages_attempted']}/{observed['pages_succeeded']}/{observed['pages_failed']}`",
                    f"- Network fetches/cache hits: `{observed['network_fetches']}/{observed['cache_hits']}`",
                    f"- Robots decisions: `{observed['robots_decisions']}`",
                    f"- Request timeout/minimum throttle: `{observed['request_timeout_seconds']}s/{observed['minimum_throttle_seconds']}s`",
                    f"- Network attempts/inter-fetch intervals: `{observed['network_fetch_attempts']}/{observed['measured_inter_network_fetch_seconds']}`",
                    f"- Minimum measured interval/throttle floor observed: `{observed['minimum_measured_inter_network_fetch_seconds']}/{observed['throttle_floor_observed']}`",
                    f"- Parsed/accepted/rejected: `{observed['parsed_records']}/{observed['accepted_records']}/{observed['rejected_records']}`",
                    f"- Duplicates/validation failures: `{observed['duplicates']}/{observed['validation_failures']}`",
                    f"- Output artifacts: `{observed['output_artifacts']}`",
                ]
            )
        elif "error" in result:
            markdown.append(f"- Error observed: `{result['error']}`")
        markdown.append("")
    markdown_text = "\n".join(markdown)
    (VERIFICATION_ROOT / "VERIFICATION_EVIDENCE.md").write_text(
        markdown_text, encoding="utf-8"
    )
    (ROOT / "VERIFICATION_EVIDENCE.md").write_text(markdown_text, encoding="utf-8")
    print(json.dumps(evidence, indent=2))
    return 0 if all(item["status"] == "PASS" for item in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())